name: End-to-end tests
on: [push]
jobs:
  cypress-run:
    runs-on: ubuntu-16.04
    steps:
      - name: Install Dependencies
        run: yarn
      - name: Checkout
        uses: actions/checkout@v2.0.0
      # Install NPM dependencies, cache them correctly
      # and run all Cypress tests
      - name: e2e tests
        uses: borales/actions-yarn@v2.0.0
        with:
          cmd: test
